name: Github Page React Deploy Workflow

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: yarn install --frozen-lockfile
      - run: yarn build
        env:
          REACT_APP_CHATGPT_API: ${{ secrets.API_KEY }}
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
